#Enable multiple megas at one time
multipleMegas = false
#Allows you to have outside megas but they devolve on battle and then you can have battle mode style theme
battleMode = true
#Enable mega evolution only for battles
battleModeOnly = false
#Allows you to have multiple primals in your team
multiplePrimals = true
#Allows you to have both the mega btn and allows u to carry your mega's into the battle, battleMode should be false for this
scuffedMode = false
